version: '3.8'

include:
    - infra.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy   
    volumes:
      - .:/app
    command: air -c .air.toml
