services:
  
  flask:
    build:
      context: ./flask
      dockerfile: flask.Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./flask:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data


  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
